import Header from "@/components/Header";
import Head from "next/head";
import coverImage from "../public/images/GeneralCoverImage.jpg";
import Image from "next/image";

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-4xl mx-auto">
        <div className="md:relative md:flex items-center justify-center p-5 md:p-0">
          <Image src={coverImage} alt="cover" />

          <div className="md:absolute top-8 left-5 max-w-sm text-md font-mono mx-auto text-justify items-center justify-center">
            Hi there, This project is created <br /> using Nextjs. Focused on
            CRUD of users <br /> data pulled from an API. <br /> <br /> Head
            over to users page <br /> to get more information...
          </div>
        </div>
        <div>
          <p className="font-serif p-5">
            The Data is pulled from{" "}
            <a
              href="https://xata.io/"
              target="_blank"
              rel="noreferrer"
              className="text-blue-400"
            >
              Xata Database{" "}
            </a>
            using Rapid API.
            <a
              href="https://github.com/NiKHiLkr23/fakeUsers-api"
              className="text-blue-400"
              rel="noreferrer"
              target="_blank"
            >
              {" "}
              Here&apos;s{" "}
            </a>
            the Github Link of API. And{" "}
            <a
              href="https://rapidapi.com/NiKHiLkr23/api/uers-api"
              className="text-blue-400"
              target="_blank"
              rel="noreferrer"
            >
              here&apos;s{" "}
            </a>
            the Rapid API Link.
          </p>
        </div>
      </main>
    </>
  );
}

export default Home;
